"""your message

Revision ID: 6813d72b29fb
Revises: a99f1b59bd3e
Create Date: 2022-04-07 17:29:50.011377

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6813d72b29fb'
down_revision = 'a99f1b59bd3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('headquarter', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('hero', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hero', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hero', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('hero', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('hero', 'headquarter')
    # ### end Alembic commands ###
